language: node_js
node_js:
  - "8.4.0"

install:
  - npm install --dev
  - npm install jsdoc -g

script:
  - yarn lint

env:
 global:
 - GH_REF: github.com/goodbotai/borq.git

deploy:
  skip_cleanup: true
  provider: script
  script:
    - yarn docs
    - yarn deploy-docs
  on:
    tags: true
