group: deprecated-2017Q3
sudo: required
language: node_js
node_js:
  - "8.4.0"

install:
  - npm install --dev

script:
  - yarn lint
  - yarn docs
  - yarn deploy-docs

env:
 global:
 - GH_REF: github.com/goodbotai/borq.git
