/** @module aggregate */
/**
 * Takes a conversation and extracts:
 * - facebook messenger id
 * - a conversation metadata object that has metadata and the conversation
 * @param {object} conversation - A conversation object generated by botkit.
 * @return {object} Messenger id and submission metadata from the conversation.
 */
function aggregate(conversation) {
  const {startTime, lastActive, responses, context} = conversation;
  const metadata = {
    start: startTime,
    stop: lastActive,
    bot_identifier: context,
    responses,
    conversation,
  };

  return {
    userId: context.user,
    submission_metadata: metadata,
  };
}

module.exports = aggregate;
